### ISSUE TITLE
param order

### ISSUE THREAD

**Issue by miladrahimi** [ErfanMomeniii/colorful#3]
I think you should change the parameter order. I mean:
```go
colorful.Println(colorful.RedColor, colorful.BlueBackground, "RedColorBlueBackground")
```
to
```go
colorful.Println("Text", colorful.RedColor, colorful.BlueBackground)
```
And the color parameters could be optional (variadic):
```go
colorful.Println("Text") // equivalent of fmt.Println
colorful.Println("Text", colorful.RedColor) // only color changed
colorful.Println("Text", colorful.RedColor, colorful.BlueBackground) // color and bg changed
```

**Comment by ErfanMomeniii** [comment]
Hi,@milad jan as you know Go doesn't support method overloading and also it doesn't support multiple variadic parameters in a function. I know that we have some alternative ways for handling that like(...interface{}) but I think that those ways are not suitable for our use case and I changed the structure for fixing that. 
now, we can use this package like the below:

1. with color and background

```go

colorful.WithColor(colorful.RedColor).
	WithBackgroundColor(colorful.BlueBackgroundColor).
	Println("RedColorBlueBackground")
```
or
```go
colorful.WithBackgroundColor(colorful.BlueBackgroundColor).
	WithColor(colorful.RedColor).
	Println("RedColorBlueBackground")
```
2. only with color:
```go
colorful.WithColor(colorful.GreenColor).
	Println("GreenColor")
```
3. only with background color:
```go
colorful.WithBackgroundColor(colorful.YellowBackgroundColor).
	Println("YellowBackground")
```

If you have any other ideas, please tell me.
 
Thanks a lot.

**Comment by miladrahimi** [comment]
Regrettably, Go does not provide support for the feature I mentioned. However, I truly appreciate your understanding of my idea, and I must say your solution appears to be excellent. Well done!
